In [2]:
import numpy as np

In [3]:
a = np.linspace(12, 24, num=12, endpoint=False)

In [4]:
a1 = np.reshape(a, (2, 6))
a2 = np.reshape(a, (3, 4))
a3 = np.reshape(a, (4, 3))
a4 = np.reshape(a, (6, 2))
a5 = np.reshape(a, (12, 1))

In [10]:
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


In [11]:
b1 = np.reshape(a, (2, -1))
b2 = np.reshape(a, (-1, 4))
b3 = np.reshape(a, (4, -1))
b4 = np.reshape(a, (-1, 2))
b5 = np.reshape(a, (12, -1))

In [12]:
print(b1)
print(b2)
print(b3)
print(b4)
print(b5)

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


In [13]:
c = np.random.rand(3, 4)

In [15]:
np.size(c)

12

In [16]:
d = np.reshape(c, (1, -1))
np.size(d)

12